// components/header.vue
<template>
    <header id="Header" class="flex flex-col w-full h-screen p-3 overflow-x-hidden">
        <div class="absolute w-full flex top-0 left-0 space-x-16">
            <h1 ref="trans-text-1" class="text-[13rem] font-bold uppercase opacity-0">Software</h1>
            <div class="w-full h-full flex flex-col justify-center items-center mt-auto mb-auto ">
                <h1 ref="trans-text-3" class="text-[5rem] font-caveat opacity-0">7 years of experience</h1>
                <h1 ref="trans-text-4" class="text-[2.5rem] font-caveat opacity-0">Gold League Player</h1>
            </div>
        </div>
        <div class="flex flex-col w-full h-full justify-center items-center">
            <h1 class="text-8xl font-bold">DrunkTaric</h1>
            <button ref="clickme-button" class="text-3xl">Click me</button>
        </div>
        <div class="absolute w-full flex bottom-0 right-0 space-x-16">
            <div class="w-full h-full flex flex-col justify-center items-center mt-auto mb-auto ">
                <h1 ref="trans-text-5" class="text-[5rem] font-caveat opacity-0">This website made with ❤️</h1>
            </div>
            <h1 ref="trans-text-2" class="text-[13rem] font-bold uppercase opacity-0">Engineer</h1>
        </div>
    </header>
</template>

<script setup>
import { useTemplateRef, onMounted } from 'vue'

let clicked = false
const header_text_1 = useTemplateRef('trans-text-1')
const header_text_2 = useTemplateRef('trans-text-2')
const header_text_3 = useTemplateRef('trans-text-3')
const header_text_4 = useTemplateRef('trans-text-4')
const header_text_5 = useTemplateRef('trans-text-5')
const clickme_button = useTemplateRef('clickme-button')

const clickme_button_animate = useMotion(clickme_button, { initial: { opacity: 1 } })
const header_text_1_animate = useMotion(header_text_1, { initial: { display: "none", opacity: 0, x: -1100 } })
const header_text_2_animate = useMotion(header_text_2, { initial: { display: "none", opacity: 0, x: 1100 } })
const header_text_3_animate = useMotion(header_text_3, { initial: { opacity: 0 } })
const header_text_4_animate = useMotion(header_text_4, { initial: { opacity: 0 } })
const header_text_5_animate = useMotion(header_text_5, { initial: { opacity: 0 } })

onMounted(() => {

    document.onscroll = async () => {
    }
    
    clickme_button.value.onclick = () => {
        if (clicked) return
        clicked = true
        header_text_1_animate.apply({ x: 0, display: "block", opacity: 1, transition: { duration: 250 } })
        header_text_2_animate.apply({ x: 0, display: "block", opacity: 1, transition: { duration: 250 } }).then(async () => {
            await header_text_3_animate.apply({ opacity: 1, transition: { duration: 500, delay: 200 } })
            await header_text_4_animate.apply({ opacity: 1, transition: { duration: 500 } })
            await header_text_5_animate.apply({ opacity: 1, transition: { duration: 500 } })
            await clickme_button_animate.apply({ opacity: 0, disabled: true, transition: { duration: 300 }})
        })
        let click_sfx = new Audio('/click.mp3');
        click_sfx.play();
        click_sfx.onended = () => {
            let music = new Audio('/music.mp3')
            music.play()
            music.loop = true
            music.volume = 0.1
        }
    }
})

</script>

// components/home/header.tsx
import { FaArrowDown } from "react-icons/fa";
import { useAnimate } from "framer-motion";
import { useEffect, useState } from "react";
import { Caveat } from 'next/font/google'
import clsx from "clsx";

const caveat = Caveat({
    subsets: ["cyrillic"],
    weight: "600",
    display: "swap"
})
  
export default function Header({ setStartedWebsite }: { StartedWebsite: boolean, setStartedWebsite: (x: boolean) => void }) {
    const [scope, animate] = useAnimate()
    const [DidScroll, setDidScroll] = useState(false)
    const [ClickedHeaderButton, setClickedHeaderButton] = useState(false);

    function StartTheHeaderAnimations() {
        if (ClickedHeaderButton) return
        setClickedHeaderButton(true)
        const music = new Audio("/music.mp3")
        const mouthClickSound = new Audio("/click.mp3")
        mouthClickSound.play()
        animate("#header_1_animated", {opacity: 1, marginLeft: 0}, {duration: 0.4})
        animate("#header_2_animated", {opacity: 1, marginRight: 0}, {duration: 0.4}).then(async () => {
          await animate("#header_3_animated", {opacity: 1}, {duration: 1})
          await animate("#header_4_animated", {opacity: 1}, {duration: 1})
          await animate("#header_5_animated", {opacity: 1}, {duration: 1})
          setStartedWebsite(true)
          await animate("#indicator", {opacity: 1}, {duration: 0.3})
        })
        music.volume = 0.2
        music.loop = true
        music.play()
    }

    useEffect(() => {
        ( () => {
            document.onscroll = async () => {
                if (DidScroll) return 
                setDidScroll(true)
                await animate("#indicator", {opacity: 0}, {duration: 0.3})
            }
        }
        )()
    }, [])


    return (
        <header ref={scope} className="flex flex-col w-full h-screen justify-center items-center z-0">
            <div className="absolute flex top-0 left-0 w-full">
              <h1 id="header_1_animated" className="font-bold -ml-[70rem] text-[11rem] uppercase opacity-0">Software</h1>
              <div className="flex flex-col items-center justify-center w-full">
                <h1 id="header_3_animated" className={clsx("text-8xl opacity-0", caveat.className)}>7 years of experience</h1>
                <h1 id="header_4_animated" className={clsx("text-6xl opacity-0", caveat.className)}>Gold league player</h1>
              </div>
            </div>
            <div id="header-center" className="flex flex-col">
              <h1 className="text-8xl font-bold">DrunkTaric</h1>
              <button 
                className="ml-auto mr-auto text-center text-2xl" 
                onClick={() => StartTheHeaderAnimations() }
              >Click Me</button>
            </div>
            <div className="absolute flex bottom-0 right-0 w-full overflow-x-hidden">
              <div className="flex flex-col items-center justify-center w-full">
                <h1 id="header_5_animated" className={clsx("text-7xl opacity-0", caveat.className)}>this website made with ❤️</h1>
              </div>
              <h1 id="header_2_animated" className="font-bold text-[11rem] uppercase opacity-0 -mr-[70rem]">Engineer</h1>
            </div>
            <div className="absolute flex bottom-0 w-full h-32">
                <div id="indicator" className="flex opacity-0 bg-white size-16 m-auto animate-bounce rounded-full">
                    {<FaArrowDown className="text-[var(--background)] text-4xl m-auto"></FaArrowDown>}
                </div>
            </div>
        </header>
    )
    
}
